-- DROP: EXPLOSION TABLE
-- ==============================
DROP TABLE Users_ServiceCenter CASCADE CONSTRAINTS;
DROP TABLE ServiceRecord_Motorcycle CASCADE CONSTRAINTS;
DROP TABLE ClubActivity_LoyaltyReward CASCADE CONSTRAINTS;
DROP TABLE ClubMembership_ClubActivity CASCADE CONSTRAINTS;
DROP TABLE Rider_ClubActivity CASCADE CONSTRAINTS;
DROP TABLE Users_Events CASCADE CONSTRAINTS;
DROP TABLE Users_Club CASCADE CONSTRAINTS;
DROP TABLE Motorcycle_ServiceCenter CASCADE CONSTRAINTS;

-- DROP EXISTING TABLES
-- ====================
DROP TABLE Login_Log CASCADE CONSTRAINTS;
DROP TABLE Notification CASCADE CONSTRAINTS;
DROP TABLE Feedback CASCADE CONSTRAINTS;
DROP TABLE User_Badge CASCADE CONSTRAINTS;
DROP TABLE Service_Record CASCADE CONSTRAINTS;
DROP TABLE Service_Appointment CASCADE CONSTRAINTS;
DROP TABLE Club_Activity CASCADE CONSTRAINTS;
DROP TABLE Loyalty_Reward CASCADE CONSTRAINTS;
DROP TABLE Referral CASCADE CONSTRAINTS;
DROP TABLE Event_Participation CASCADE CONSTRAINTS;
DROP TABLE Badge CASCADE CONSTRAINTS;
DROP TABLE Club_Membership CASCADE CONSTRAINTS;
DROP TABLE Club CASCADE CONSTRAINTS;
DROP TABLE Merchandise_Purchase CASCADE CONSTRAINTS;
DROP TABLE Merchandise CASCADE CONSTRAINTS;
DROP TABLE Event CASCADE CONSTRAINTS;
DROP TABLE Motorcycle CASCADE CONSTRAINTS;
DROP TABLE Service_Center CASCADE CONSTRAINTS;
DROP TABLE Rider CASCADE CONSTRAINTS;
DROP TABLE Admin CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;
